//
// Created by Sourabh on 03-11-2022.
//

#ifndef CODING_WEBSITE_KTHSMALLESTANDLARGEST_H
#define CODING_WEBSITE_KTHSMALLESTANDLARGEST_H


class KthSmallestAndLargest {

};


#endif //CODING_WEBSITE_KTHSMALLESTANDLARGEST_H
